CFLAGS= -std=gnu11 -O0 -Wall -Wextra -Wpedantic -g
#-std=c11 change later now for testing is gnu11 needed

.PHONY:  all clean
all:clean main
main: main.c ludecomp.h test.h ludecomp_intrinsics.h ludecomp_2.h
clean:
	rm -f main

